[package]
name = "code_outline"
version = "0.1.0"
edition = "2024"
description = "Code-symbol outlines of repositories"
publish.workspace = true
license.workspace = true

[features]
jemalloc = []

[dependencies]
ignore = "0.4.23"
itertools.workspace = true
lazy_static.workspace = true
rayon.workspace = true
repo_metadata.workspace = true
serde.workspace = true
anyhow.workspace = true
arborium.workspace = true
futures.workspace = true
languages.workspace = true
streaming-iterator.workspace = true
syntax_tree.workspace = true
warp_errors.workspace = true
warp_util.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true
