//! Generators reviewed to run only a command that reads the local machine (files, the
//! repository, local daemons) and that takes no user tokens, or takes them only safely.
//!
//! Sorted by `(spec, generator)`; [`super::is_generator_allowed`] binary-searches it. The spec is
//! the name a `warp-command-signatures` spec registers its generators under (lowercase).
//! Everything not listed here is denied, see the module documentation of [`super`] for the
//! policy and for how to classify a new entry.

pub(super) const ALLOWED_GENERATORS: &[(&str, &str)] = &[
    ("apt", "list"),
    ("apt", "list_prefix"),
    ("apt", "list_upgradable"),
    ("apt-get", "list_all_deb_files_in_cwd"),
    ("apt-get", "list_all_packages"),
    ("apt-get", "list_available_packages"),
    ("aptitude", "list_all_deb_files_in_cwd"),
    ("aptitude", "list_all_packages"),
    ("aptitude", "list_available_packages"),
    ("asdf", "installed_plugins"),
    ("asdf", "shims"),
    ("assimp", "listexport"),
    ("assimp", "listext"),
    ("aws", "profiles"),
    ("bat", "completions"),
    ("bat", "completions_bat"),
    ("bat", "unknow_dev_null_possible"),
    ("bat", "unknow_dev_null_possible_bat"),
    ("bat", "unknow_dev_null_possible_color"),
    ("bat", "unknow_dev_null_possible_italic"),
    ("bat", "unknow_dev_null_possible_wrap"),
    ("bazel", "build_file"),
    ("bun", "dependencies_generator"),
    ("bun", "get_scripts_generator"),
    ("checkov", "git_branch"),
    ("chown", "users_or_groups"),
    ("clear-variable", "get_variable_names"),
    ("conda", "get_conda_configs"),
    ("conda", "get_conda_environments"),
    ("conda", "get_installed_packages"),
    ("copilot", "cat_copilot_workspace"),
    ("cordova", "cat_package_json"),
    ("debug-process", "get_process_names"),
    ("defaults", "domain_generator"),
    ("deno", "deno_binaries"),
    ("deta", "node12_node14_python3_7_python3"),
    ("docker", "all_docker_contexts"),
    ("docker", "from_as"),
    ("dtm", "list_plugins"),
    ("elm-review", "echo"),
    ("enter-pshostprocess", "get_process_names"),
    ("expo", "sysctl_hw_ncpu"),
    ("expo", "xcrun_xctrace_list_devices"),
    ("expo-cli", "sysctl_hw_ncpu"),
    ("expo-cli", "xcrun_xctrace_list_devices"),
    ("ffmpeg", "completions"),
    ("ffmpeg", "completions_devices"),
    ("fisher", "fish_fisher_list"),
    ("fnm", "ls"),
    ("get-help", "get_command_names"),
    ("get-process", "get_process_names"),
    ("get-variable", "get_variable_names"),
    ("gh", "git_branch"),
    ("gh", "list_alias"),
    ("git", "aliases"),
    ("git", "commits"),
    ("git", "local_branches"),
    ("git", "local_or_remote_branch"),
    ("git", "push_refspec_branches"),
    ("git", "push_refspec_tags"),
    ("git", "refs_remote_branches"),
    ("git", "remote_branches"),
    ("git", "remotes"),
    ("git", "revs"),
    ("git", "settings_generator"),
    ("git", "stashes"),
    ("git", "tags"),
    ("git", "worktrees"),
    ("git-flow", "type_branches"),
    ("gpg", "completions"),
    ("gt", "commits"),
    ("gt", "local_branches"),
    ("hub", "aliases"),
    ("hub", "branches"),
    ("hub", "branches_no"),
    ("hub", "log"),
    ("hub", "remotes"),
    ("hub", "revs"),
    ("hub", "settings_generator"),
    ("hub", "stashes"),
    ("hub", "tag"),
    ("hugo", "ls_archetypes"),
    ("hyper", "list"),
    ("id", "dscl_users"),
    ("ignite-cli", "ls_ignite_templates"),
    ("ip", "netns"),
    ("ip", "network_interfaces"),
    ("ip", "processes"),
    ("ip", "tunnel_interfaces"),
    ("j", "cat"),
    ("journalctl", "boots"),
    ("journalctl", "journal_field_matches"),
    ("journalctl", "journal_fields"),
    ("journalctl", "syslog_identifiers"),
    ("journalctl", "units"),
    ("journalctl", "user_units"),
    ("kill", "process"),
    ("kill", "signal_name"),
    ("killall", "process_name"),
    ("killall", "user_name"),
    ("kubectx", "context"),
    ("kubectx", "delete_context"),
    ("kubectx", "kubectx_context"),
    ("kubens", "context"),
    ("lerna", "git_branch"),
    ("lerna", "git_remote"),
    ("limactl", "list"),
    ("lsof", "pids"),
    ("lsof", "process_names"),
    ("lsof", "users"),
    ("mackup", "list"),
    ("make", "list_targets"),
    ("man", "list_man_pages"),
    ("mdfind", "ls_library_saved_searches_savedsearch"),
    ("mosh", "cat_ssh_config"),
    ("mosh", "cat_ssh_known_hosts"),
    ("networkquality", "networksetup"),
    ("nmap", "network_interfaces"),
    ("nmap", "nse_scripts"),
    ("npm", "get_scripts_generator"),
    ("npx", "until_node_modules_do_cd"),
    ("nr", "until_package_json_do_cd"),
    ("nx", "local_generators"),
    ("nx", "local_schematics"),
    ("open", "mdfind"),
    ("open", "mdfind_while_read_line"),
    ("pacman", "list_all_packages"),
    ("pacman", "list_all_pkg_tar_files_in_cwd"),
    ("pacman", "list_installed_packages"),
    ("pandoc", "completions"),
    ("pandoc", "completions_list"),
    ("pandoc", "pandoc"),
    ("paru", "list_all_pkg_tar_files_in_cwd"),
    ("paru", "list_installed_packages"),
    ("pass", "entries"),
    ("pass", "entry_dirs"),
    ("pkill", "process_name"),
    ("pkill", "signal_name"),
    ("pkill", "user_name"),
    ("pnpm", "dependencies_generator"),
    ("pnpm", "get_scripts_generator"),
    ("pnpm", "search_branches"),
    ("pnpm", "until_package_json_do_cd"),
    ("pnpm", "workspace_packages_generator"),
    ("pprof", "saved_profiles"),
    ("pre-commit", "cat_pre_commit_config_yaml"),
    ("pre-commit", "git_branch"),
    ("pre-commit", "git_branch_no"),
    ("pre-commit", "git_remote"),
    ("pre-commit", "git_rev_list"),
    ("projj", "cat_projj_cache_json"),
    ("projj", "cat_projj_config_json"),
    ("pyenv", "global_list"),
    ("pyenv", "version_list"),
    ("rancher", "server"),
    ("rclone", "listremotes"),
    ("react-native", "android_get_devices_generator"),
    ("react-native", "ios_get_devices_generator"),
    ("react-native", "ios_get_devices_simulator_generator"),
    ("react-native", "ios_get_devices_udid_generator"),
    ("react-native", "worker_generator"),
    ("redwood", "until_redwood_toml_do_cd"),
    ("remove-variable", "get_variable_names"),
    ("robot", "for_i_in_robot"),
    ("robot", "test_cases"),
    ("robot", "variables"),
    ("ros2", "interfaces"),
    ("ros2", "packages"),
    ("rush", "until_rush_json_do_cd"),
    ("rushx", "until_package_json_do_cd"),
    ("scc", "completions"),
    ("scp", "hosts"),
    ("screen", "detached_sessions"),
    ("screen", "sessions"),
    ("sdk", "candidates"),
    ("set-variable", "get_variable_names"),
    ("sftp", "cat_ssh_config"),
    ("sftp", "cat_ssh_known_hosts"),
    ("shortcuts", "list"),
    ("shortcuts", "list_shortcuts"),
    ("ssh", "addresses"),
    ("ssh", "hosts"),
    ("ssh", "known_hosts"),
    ("st2", "users_or_groups"),
    ("sysctl", "completions"),
    ("systemctl", "unit_states"),
    ("systemctl", "unit_types"),
    ("systemctl", "units"),
    ("tailscale", "peers_colon"),
    ("tailscale", "status"),
    ("tar", "list_tar_files"),
    ("tccutil", "mdfind_applications_while_read"),
    ("tcpdump", "interfaces"),
    ("tcpdump", "user_name"),
    ("tfenv", "list"),
    ("timedatectl", "timezones"),
    ("tmux", "buffer_name"),
    ("tmux", "src_pane"),
    ("tmux", "target_client"),
    ("tmux", "target_session"),
    ("tmux", "window_name"),
    ("tmuxinator", "projects"),
    ("tmuxinator", "session_names"),
    ("tokei", "completions"),
    ("trex", "cat_import_map_json"),
    ("trex", "cat_run_json"),
    ("turbo", "git_branch"),
    ("turbo", "until_turbo_json_do_cd"),
    ("uv", "installed_pythons"),
    ("uv", "installed_tools"),
    ("uv", "pip_installed_packages"),
    ("uv", "python_versions"),
    ("vagrant", "vagrant_boxes"),
    ("vagrant", "vagrant_machines"),
    ("vite", "ls"),
    ("vr", "completions"),
    ("vsce", "git_branch"),
    ("wait-process", "get_process_names"),
    ("watson", "log"),
    ("watson", "projects"),
    ("watson", "tags"),
    ("wd", "cat_warprc"),
    (
        "wifi-password",
        "networksetup_wi_fi_getline_print_networksetup",
    ),
    ("yarn", "dependencies_generator"),
    ("yarn", "executables_within_node_modules"),
    ("yarn", "get_scripts_generator"),
    ("yay", "list_all_pkg_tar_files_in_cwd"),
    ("yay", "list_installed_packages"),
    ("youtube-dl", "pbpaste"),
];

/// Generators that run only when the context reports that the operating system keeps the
/// command from reaching a network (`GeneratorContext::network_isolated`: macOS and Linux local
/// sessions, never Windows) and the offline environment table is applied. Each looks local but
/// was shown to reach a network, or to run repository code, in the environment alone:
///
/// * `cargo/*`, `rustup/rustup_docs`: the rustup proxies install the toolchain a project's
///   `rust-toolchain.toml` names (two GETs per command against a loopback canary).
/// * `npm/workspace_generator`: `npm prefix` ends with an update-check request.
/// * `git/tracked_files`, `git/treeish`, `hub/treeish`: `git ls-files` and `git diff --cached`
///   run the `core.fsmonitor` program of a repository's config.
///
/// The real tools were run against a canary with the sandbox and the environment table each on
/// its own and both together (`network_sandbox_tests.rs`, `offline_environment_tests.rs`,
/// `restored_generators_tests.rs` in the app crate), and each pair here is checked by that last
/// test against the command the bundled spec runs. Sorted, and disjoint from [`ALLOWED_GENERATORS`].
pub(super) const ALLOWED_WHEN_ISOLATED: &[(&str, &str)] = &[
    ("cargo", "bin_list"),
    ("cargo", "features_generators"),
    ("cargo", "read_manifest"),
    ("cargo", "spec"),
    ("cargo", "target_list"),
    ("cargo", "test_targets"),
    ("git", "tracked_files"),
    ("git", "treeish"),
    ("hub", "treeish"),
    ("npm", "workspace_generator"),
    ("rustup", "rustup_docs"),
];

/// Alias generators that may run. Empty: the bundled ones interpolate the typed word unquoted
/// (`git`) or run `npm prefix` (`npm`, `yarn`).
pub(super) const ALLOWED_ALIAS_GENERATORS: &[(&str, &str)] = &[];

/// The subset of [`ALLOWED_GENERATORS`] that also runs on Windows: commands built only from file
/// reads (`cat`, `ls`, `find`, `grep`, ...) and PowerShell process and variable cmdlets, none of
/// which takes the user's tokens. Windows has no network sandbox (SEC-SBX covers macOS and
/// Linux), so a generator that starts any other program is not allowed there. Sorted.
pub(super) const ALLOWED_ON_WINDOWS: &[(&str, &str)] = &[
    ("apt-get", "list_all_deb_files_in_cwd"),
    ("aptitude", "list_all_deb_files_in_cwd"),
    ("asdf", "shims"),
    ("aws", "profiles"),
    ("bun", "dependencies_generator"),
    ("bun", "get_scripts_generator"),
    ("clear-variable", "get_variable_names"),
    ("copilot", "cat_copilot_workspace"),
    ("cordova", "cat_package_json"),
    ("debug-process", "get_process_names"),
    ("deno", "deno_binaries"),
    ("deta", "node12_node14_python3_7_python3"),
    ("elm-review", "echo"),
    ("enter-pshostprocess", "get_process_names"),
    ("get-process", "get_process_names"),
    ("get-variable", "get_variable_names"),
    ("hugo", "ls_archetypes"),
    ("ignite-cli", "ls_ignite_templates"),
    ("j", "cat"),
    ("make", "list_targets"),
    ("mdfind", "ls_library_saved_searches_savedsearch"),
    ("mosh", "cat_ssh_config"),
    ("npm", "get_scripts_generator"),
    ("npx", "until_node_modules_do_cd"),
    ("nr", "until_package_json_do_cd"),
    ("nx", "local_generators"),
    ("nx", "local_schematics"),
    ("pacman", "list_all_pkg_tar_files_in_cwd"),
    ("paru", "list_all_pkg_tar_files_in_cwd"),
    ("pnpm", "dependencies_generator"),
    ("pnpm", "get_scripts_generator"),
    ("pnpm", "until_package_json_do_cd"),
    ("pre-commit", "cat_pre_commit_config_yaml"),
    ("projj", "cat_projj_cache_json"),
    ("projj", "cat_projj_config_json"),
    ("redwood", "until_redwood_toml_do_cd"),
    ("remove-variable", "get_variable_names"),
    ("robot", "for_i_in_robot"),
    ("robot", "test_cases"),
    ("rush", "until_rush_json_do_cd"),
    ("rushx", "until_package_json_do_cd"),
    ("scp", "hosts"),
    ("set-variable", "get_variable_names"),
    ("sftp", "cat_ssh_config"),
    ("ssh", "addresses"),
    ("ssh", "hosts"),
    ("ssh", "known_hosts"),
    ("tar", "list_tar_files"),
    ("trex", "cat_import_map_json"),
    ("trex", "cat_run_json"),
    ("turbo", "until_turbo_json_do_cd"),
    ("vite", "ls"),
    ("wait-process", "get_process_names"),
    ("wd", "cat_warprc"),
    ("yarn", "dependencies_generator"),
    ("yarn", "executables_within_node_modules"),
    ("yarn", "get_scripts_generator"),
    ("yay", "list_all_pkg_tar_files_in_cwd"),
];
