//! Generators that must not run, with the reason, and the alias generators that must not run.
//!
//! These lists are not consulted at runtime (anything not in `allowed.rs` is denied). They let
//! the drift test tell a reviewed generator from one that nobody has classified yet after a
//! `warp-command-signatures` bump. Sorted by `(spec, generator)`.
//!
//! Classes (a generator carries the first that applies in this order):
//!
//! * `network`: contacts a remote service. `cluster`: queries the user's own cluster API server.
//!   `maybe-network`: may reach a network depending on configuration (remote backends, package
//!   fetching). `lan`: uses local network discovery.
//! * `env-network-verified`: the command looks local but the tool reached a network (or, for
//!   `npm`, a registry) when run against a loopback canary: rustup proxies install a toolchain
//!   named by `rust-toolchain.toml`, `docker` talks to whatever `DOCKER_HOST` or the current
//!   context names, `npm` runs its update check, a corepack shim downloads the package manager
//!   named by `packageManager`.
//! * `project-code`: runs code the project controls, or cannot be shown not to: interpreters
//!   that load project files (`nx`, `lerna`, `Rscript` loads `./.Rprofile`, `python3 -c` imports
//!   from the working directory first), and `git status`, `diff` and `ls-files`, which run the
//!   `core.fsmonitor` program of a repository's own config.
//! * `env-network-likely`: a tool with a documented update check, telemetry, toolchain download,
//!   remote include or remote mode, or one nobody reviewed. Not run against a canary here.
//! * `injectable`: interpolates the user's unsubmitted tokens into the shell command without
//!   quoting them, so typing a crafted word runs a command before the line is submitted.

pub(super) const DENIED_GENERATORS: &[(&str, &str, &str)] = &[
    ("amplify", "env_list", "maybe-network"),
    ("ansible-doc", "completions", "project-code"),
    ("asdf", "all_versions", "maybe-network"),
    ("asdf", "available_plugins", "maybe-network"),
    ("asdf", "installed_versions", "injectable"),
    ("aws", "ec2_images", "network"),
    ("aws", "ec2_instances", "network"),
    ("aws", "ec2_key_pairs", "network"),
    ("aws", "ec2_running_instances", "network"),
    ("aws", "ec2_security_groups", "network"),
    ("aws", "ec2_snapshots", "network"),
    ("aws", "ec2_stopped_instances", "network"),
    ("aws", "ec2_subnets", "network"),
    ("aws", "ec2_volumes", "network"),
    ("aws", "ec2_vpcs", "network"),
    ("aws", "s3_buckets", "network"),
    ("az", "acr_registries", "network"),
    ("az", "aks_clusters", "network"),
    ("az", "available_extensions", "network"),
    ("az", "functionapps", "network"),
    ("az", "installed_extensions", "env-network-likely"),
    ("az", "keyvaults", "network"),
    ("az", "resource_groups", "network"),
    ("az", "storage_accounts", "network"),
    ("az", "subscriptions", "env-network-likely"),
    ("az", "vms", "network"),
    ("az", "webapps", "network"),
    ("black", "gh_release_list_psf_black", "network"),
    ("bosh", "deployments", "network"),
    ("brew", "all_casks_generator", "maybe-network"),
    ("brew", "brew_info_generator", "maybe-network"),
    ("brew", "formulae_generator", "env-network-likely"),
    ("brew", "gist_logs_actions", "injectable"),
    ("brew", "outdated_formula_generator", "maybe-network"),
    ("brew", "repositories_generator", "env-network-likely"),
    ("brew", "services", "env-network-likely"),
    ("brew", "uninstall_cask", "env-network-likely"),
    ("bun", "npms_search", "network"),
    ("cargo", "bin_list", "env-network-verified"),
    ("cargo", "crates_io_search", "network"),
    ("cargo", "dependencies", "maybe-network"),
    ("cargo", "features_generators", "env-network-verified"),
    ("cargo", "read_manifest", "env-network-verified"),
    ("cargo", "spec", "env-network-verified"),
    ("cargo", "target_list", "env-network-verified"),
    ("cargo", "test_list", "maybe-network"),
    ("cargo", "test_targets", "env-network-verified"),
    ("claude", "installed_plugins", "env-network-likely"),
    ("claude", "mcp_servers", "maybe-network"),
    ("codex", "cloud_tasks", "network"),
    ("codex", "commits", "env-network-likely"),
    ("codex", "feature_flags", "env-network-likely"),
    ("codex", "local_branches", "env-network-likely"),
    ("codex", "mcp_servers", "env-network-likely"),
    ("cordova", "plugin_list", "project-code"),
    ("dd", "conv_remaining", "injectable"),
    ("degit", "github_user_repos", "network"),
    ("deno", "deno_versions", "network"),
    ("deno", "doc_json", "maybe-network"),
    ("deno", "lint", "env-network-likely"),
    ("deployctl", "deploy_versions", "network"),
    ("dnf", "list_installed_packages", "env-network-likely"),
    ("dnf", "list_rpm_files_in_cwd", "env-network-likely"),
    ("docker", "all_docker_containers", "env-network-verified"),
    ("docker", "all_local_images", "env-network-verified"),
    ("docker", "docker_images", "env-network-verified"),
    ("docker", "docker_volumes", "env-network-verified"),
    ("docker", "image_with_tags", "env-network-verified"),
    ("docker", "list_docker_networks", "env-network-verified"),
    ("docker", "list_docker_plugins", "env-network-verified"),
    ("docker", "list_docker_secrets", "maybe-network"),
    ("docker", "list_docker_service_replicas", "maybe-network"),
    ("docker", "list_docker_services", "maybe-network"),
    ("docker", "list_docker_stacks", "maybe-network"),
    ("docker", "list_docker_swarm_nodes", "maybe-network"),
    ("docker", "list_docker_volumes", "env-network-verified"),
    ("docker", "paused_docker_containers", "env-network-verified"),
    ("docker", "remove_images", "env-network-verified"),
    (
        "docker",
        "running_docker_containers",
        "env-network-verified",
    ),
    ("docker", "search", "network"),
    ("docker-compose", "compose_services", "env-network-likely"),
    ("dotnet", "global_tools", "env-network-likely"),
    ("eb", "list", "network"),
    ("elm", "elm_packages", "network"),
    ("esbuild", "loader", "injectable"),
    ("eslint", "env_remaining", "injectable"),
    (
        "eslint",
        "ls_node_modules_root_global",
        "env-network-verified",
    ),
    ("expo", "npms_search", "network"),
    ("expo", "xcodebuild_ios_xcodeproj", "maybe-network"),
    ("expo-cli", "npms_search", "network"),
    ("expo-cli", "xcodebuild_ios_xcodeproj", "maybe-network"),
    ("fig-teams@latest", "teams_list", "network"),
    ("fig-teams@latest", "users_for_selected_team", "network"),
    ("file", "param_keys", "injectable"),
    ("firebase", "project_aliases", "network"),
    ("flutter", "channels", "maybe-network"),
    ("flutter", "emulators", "env-network-likely"),
    ("fly", "flyctl_list_apps", "network"),
    ("fly", "flyctl_list_orgs", "network"),
    ("flyctl", "list_apps", "network"),
    ("flyctl", "list_orgs", "network"),
    ("fnm", "ls_remote", "network"),
    ("fvm", "releases", "maybe-network"),
    ("gcloud", "gcloud_accounts", "env-network-likely"),
    ("gcloud", "gcloud_components", "maybe-network"),
    ("gcloud", "gcloud_configurations", "env-network-likely"),
    ("gcloud", "gcloud_projects", "network"),
    ("gcloud", "gcloud_regions", "network"),
    ("gcloud", "gcloud_zones", "network"),
    ("gh", "api_graphql_string_viewer", "network"),
    ("gh", "list_pr", "network"),
    ("gh", "repo_list_owner", "network"),
    ("git", "files_for_staging", "project-code"),
    ("git", "get_changed_or_tracked_files", "project-code"),
    ("git", "tracked_files", "project-code"),
    ("git", "treeish", "project-code"),
    ("go", "tool_generator", "env-network-likely"),
    ("gsutil", "gcloud_projects", "network"),
    ("gsutil", "gcs_buckets", "network"),
    ("heroku", "get_app_generator", "network"),
    ("hexo", "list_post_draft", "project-code"),
    ("hub", "status", "project-code"),
    ("hub", "status_staged_or_unstaged", "project-code"),
    ("hub", "treeish", "project-code"),
    ("just", "recipes", "project-code"),
    ("just", "variables", "project-code"),
    ("kool", "docker_compose_config", "env-network-likely"),
    ("kool", "run", "project-code"),
    ("kubecolor", "cluster", "injectable"),
    ("kubecolor", "cluster_role", "cluster"),
    ("kubecolor", "context", "injectable"),
    ("kubecolor", "deployments", "cluster"),
    ("kubecolor", "namespace", "cluster"),
    ("kubecolor", "node", "cluster"),
    ("kubecolor", "resource", "cluster"),
    ("kubecolor", "resource_type", "cluster"),
    ("kubecolor", "role", "cluster"),
    ("kubecolor", "running_pods", "cluster"),
    ("kubecolor", "type_or_type_slash_name", "cluster"),
    ("kubecolor", "user", "injectable"),
    ("kubectl", "cluster", "injectable"),
    ("kubectl", "cluster_role", "cluster"),
    ("kubectl", "context", "injectable"),
    ("kubectl", "deployments", "cluster"),
    ("kubectl", "kubectl_builtin_completion", "cluster"),
    ("kubectl", "namespace", "cluster"),
    ("kubectl", "node", "cluster"),
    ("kubectl", "resource", "cluster"),
    ("kubectl", "resource_type", "cluster"),
    ("kubectl", "role", "cluster"),
    ("kubectl", "running_pods", "cluster"),
    ("kubectl", "type_or_type_slash_name", "cluster"),
    ("kubectl", "user", "injectable"),
    ("kubens", "kubens_context", "cluster"),
    ("lerna", "list_while_read_p", "project-code"),
    ("lerna", "ls", "project-code"),
    ("man", "sections_remaining", "injectable"),
    ("meteor", "cat_meteor_packages", "env-network-likely"),
    ("meteor", "create", "maybe-network"),
    ("meteor", "list_platforms", "env-network-likely"),
    ("mix", "help", "project-code"),
    ("n", "lsr", "network"),
    ("nativescript", "nativescript_templates", "network"),
    ("nextflow", "downloaded_projects", "env-network-likely"),
    ("nextflow", "run_names", "env-network-likely"),
    ("ng", "list_projects", "env-network-likely"),
    ("ni", "npms_search", "network"),
    ("npm", "npm_registry_search", "network"),
    ("npm", "npms_search", "network"),
    ("npm", "workspace_generator", "env-network-verified"),
    ("ns", "nativescript_templates", "network"),
    ("nx", "apps", "project-code"),
    ("nx", "apps_and_libs", "project-code"),
    ("nx", "e2e_apps", "project-code"),
    ("nx", "installed_plugins", "project-code"),
    ("nx", "plugin_list", "project-code"),
    ("nx", "workspace_targets", "project-code"),
    ("oc", "build_configs", "cluster"),
    ("oc", "cluster", "injectable"),
    ("oc", "cluster_role", "cluster"),
    ("oc", "context", "injectable"),
    ("oc", "deployments", "cluster"),
    ("oc", "namespace", "cluster"),
    ("oc", "node", "cluster"),
    ("oc", "oc_builtin_completion", "cluster"),
    ("oc", "projects", "cluster"),
    ("oc", "resource", "cluster"),
    ("oc", "resource_type", "cluster"),
    ("oc", "role", "cluster"),
    ("oc", "running_pods", "cluster"),
    ("oc", "type_or_type_slash_name", "cluster"),
    ("oc", "user", "injectable"),
    ("okteto", "context_list", "env-network-likely"),
    ("okteto", "namespace_list", "network"),
    ("op", "account_list_json", "env-network-likely"),
    ("paru", "list_all_packages", "env-network-likely"),
    ("phpunit-watcher", "tests", "project-code"),
    ("pip", "list_packages", "maybe-network"),
    ("pip3", "list_packages", "maybe-network"),
    ("pnpm", "npms_search", "network"),
    ("quickmail", "template_listall", "env-network-likely"),
    ("r", "rscript_libpaths", "project-code"),
    ("react-native", "gradle_tasks_generator", "maybe-network"),
    ("react-native", "xcode_config_generator", "maybe-network"),
    ("react-native", "xcode_scheme_generator", "maybe-network"),
    ("ros2", "actions", "lan"),
    ("ros2", "executables", "injectable"),
    ("ros2", "nodes", "lan"),
    ("ros2", "services", "lan"),
    ("ros2", "topics", "lan"),
    ("rush", "npms_search", "network"),
    ("rustup", "rustup_docs", "env-network-verified"),
    ("scc", "format_multi", "injectable"),
    ("scp", "remote_paths", "network"),
    ("sdk", "available_versions", "network"),
    ("sdk", "installed_versions", "injectable"),
    ("softwareupdate", "completions", "network"),
    ("stepzen", "github_schemas", "network"),
    ("stepzen", "list_schemas", "network"),
    ("terraform", "address_list", "maybe-network"),
    ("terraform", "output_list", "maybe-network"),
    ("terraform", "workspace_list", "maybe-network"),
    ("terragrunt", "state_list", "maybe-network"),
    ("terragrunt", "workspace_list", "maybe-network"),
    ("tfenv", "list_remote", "network"),
    ("tfsec", "terraform_workspace_list", "maybe-network"),
    ("tns", "nativescript_templates", "network"),
    ("trivy", "pkg_types_remaining", "injectable"),
    ("trivy", "scanners_remaining", "injectable"),
    ("trivy", "severity_remaining", "injectable"),
    ("tsh", "clusters", "network"),
    ("tsh", "nodes", "network"),
    ("tsh", "status_user", "env-network-likely"),
    ("uv", "project_dependencies", "project-code"),
    ("vultr-cli", "instance_list", "network"),
    ("yarn", "all_dependencies_generator", "env-network-verified"),
    ("yarn", "config_list", "env-network-verified"),
    ("yarn", "create_package_search", "network"),
    (
        "yarn",
        "get_global_packages_generator",
        "env-network-verified",
    ),
    ("yarn", "npms_search", "network"),
    ("yarn", "workspace_names_generator", "env-network-verified"),
    ("yay", "list_all_packages", "env-network-likely"),
    ("yc", "yc_builtin_completion", "maybe-network"),
    ("yo", "completions", "env-network-likely"),
    ("youtube-dl", "flat_playlist", "network"),
];

/// Alias generators that must not run, with the class. An alias generator is a command the
/// completion engine runs to expand an alias typed by the user.
pub(super) const DENIED_ALIAS_GENERATORS: &[(&str, &str, &str)] = &[
    ("git", "alias", "injectable"),
    ("npm", "script_alias", "env-network-verified"),
    ("yarn", "script_alias", "env-network-verified"),
];
