//! Generators that must not run, with the reason, and the alias generators that must not run.
//!
//! These lists are not consulted at runtime (anything not in `allowed.rs` is denied). They let
//! the drift test tell a reviewed generator from one that nobody has classified yet after a
//! `warp-command-signatures` bump. Sorted by `(spec, generator)`.
//!
//! Classes (a generator carries the first that applies in this order):
//!
//! * `network`: contacts a remote service. `cluster`: queries the user's own cluster API server.
//!   `maybe-network`: may reach a network depending on configuration (remote backends, package
//!   fetching). `lan`: uses local network discovery.
//! * `env-network-verified`: the command looks local but the tool reached a network (or, for
//!   `npm`, a registry) when run against a loopback canary: rustup proxies install a toolchain
//!   named by `rust-toolchain.toml`, `docker` talks to whatever `DOCKER_HOST` or the current
//!   context names, `npm` runs its update check, a corepack shim downloads the package manager
//!   named by `packageManager`. The pairs that were later shown to be quiet with the OS network
//!   sandbox and the offline environment table are in `ALLOWED_WHEN_ISOLATED` (`allowed.rs`)
//!   instead. The `yarn` ones stay here: yarn also runs the project's `yarn-path` script
//!   (measured: `yarn config list`, `list` and `workspaces info` each executed it).
//! * `project-code`: runs code the project controls, or cannot be shown not to: interpreters
//!   that load project files (`nx`, `lerna`, `Rscript` loads `./.Rprofile`, `python3 -c` imports
//!   from the working directory first), and `git status`, `diff` and `ls-files`, which run the
//!   `core.fsmonitor` program of a repository's own config. The `git status`-like ones also run
//!   a repository's `clean` filter (measured, and not switched off by the environment table);
//!   `ls-files` and `diff --cached`, which the table makes quiet, are in `ALLOWED_WHEN_ISOLATED`.
//!   Also the tools that *discover* an interpreter or toolchain when asked a question, which
//!   start whatever the project points them at (measured with the real tools, cold caches,
//!   `project_code_tests.rs`): `uv pip list` and `uv python list` start the `.venv` or
//!   `PATH` Python of the project and run its `sitecustomize.py`, and `[pip] python` in a
//!   `uv.toml` or `pyproject.toml` names any executable; the rustup proxies behind every
//!   `cargo` generator start the `cargo` of a `path =` toolchain in `rust-toolchain.toml`;
//!   `npm prefix` runs the `onload-script` of a project's `.npmrc` in npm 6; `conda` is a
//!   Python tool that was not run here. `bazel/build_file` pipes project file names into
//!   `xargs -I {} sh -c '... "{}"'`, so a directory named `$(...)` runs a command.
//! * `env-network-likely`: a tool with a documented update check, telemetry, toolchain download,
//!   remote include or remote mode, or one nobody reviewed. Not run against a canary here.
//! * `injectable`: interpolates the user's unsubmitted tokens into the shell command without
//!   quoting them, so typing a crafted word runs a command before the line is submitted.

pub(super) const DENIED_GENERATORS: &[(&str, &str, &str)] = &[
    ("amplify", "env_list", "maybe-network"),
    ("ansible-doc", "completions", "project-code"),
    ("apt", "list", "unverified-tool"),
    ("apt", "list_prefix", "unverified-tool"),
    ("apt", "list_upgradable", "unverified-tool"),
    ("apt-get", "list_all_deb_files_in_cwd", "unverified-tool"),
    ("apt-get", "list_all_packages", "unverified-tool"),
    ("apt-get", "list_available_packages", "unverified-tool"),
    ("aptitude", "list_all_deb_files_in_cwd", "unverified-tool"),
    ("aptitude", "list_all_packages", "unverified-tool"),
    ("aptitude", "list_available_packages", "unverified-tool"),
    ("asdf", "all_versions", "maybe-network"),
    ("asdf", "available_plugins", "maybe-network"),
    ("asdf", "installed_plugins", "unverified-tool"),
    ("asdf", "installed_versions", "unverified-tool"),
    ("asdf", "shims", "unverified-tool"),
    ("assimp", "listexport", "unverified-tool"),
    ("assimp", "listext", "unverified-tool"),
    ("aws", "ec2_images", "network"),
    ("aws", "ec2_instances", "network"),
    ("aws", "ec2_key_pairs", "network"),
    ("aws", "ec2_running_instances", "network"),
    ("aws", "ec2_security_groups", "network"),
    ("aws", "ec2_snapshots", "network"),
    ("aws", "ec2_stopped_instances", "network"),
    ("aws", "ec2_subnets", "network"),
    ("aws", "ec2_volumes", "network"),
    ("aws", "ec2_vpcs", "network"),
    ("aws", "profiles", "unverified-tool"),
    ("aws", "s3_buckets", "network"),
    ("az", "acr_registries", "network"),
    ("az", "aks_clusters", "network"),
    ("az", "available_extensions", "network"),
    ("az", "functionapps", "network"),
    ("az", "installed_extensions", "env-network-likely"),
    ("az", "keyvaults", "network"),
    ("az", "resource_groups", "network"),
    ("az", "storage_accounts", "network"),
    ("az", "subscriptions", "env-network-likely"),
    ("az", "vms", "network"),
    ("az", "webapps", "network"),
    ("bat", "completions", "unverified-tool"),
    ("bat", "completions_bat", "unverified-tool"),
    ("bat", "unknow_dev_null_possible", "unverified-tool"),
    ("bat", "unknow_dev_null_possible_bat", "unverified-tool"),
    ("bat", "unknow_dev_null_possible_color", "unverified-tool"),
    ("bat", "unknow_dev_null_possible_italic", "unverified-tool"),
    ("bat", "unknow_dev_null_possible_wrap", "unverified-tool"),
    ("bazel", "build_file", "project-code"),
    ("black", "gh_release_list_psf_black", "network"),
    ("bosh", "deployments", "network"),
    ("brew", "all_casks_generator", "maybe-network"),
    ("brew", "brew_info_generator", "maybe-network"),
    ("brew", "formulae_generator", "env-network-likely"),
    ("brew", "gist_logs_actions", "unverified-tool"),
    ("brew", "outdated_formula_generator", "maybe-network"),
    ("brew", "repositories_generator", "env-network-likely"),
    ("brew", "services", "env-network-likely"),
    ("brew", "uninstall_cask", "env-network-likely"),
    ("bun", "dependencies_generator", "unverified-tool"),
    ("bun", "get_scripts_generator", "unverified-tool"),
    ("bun", "npms_search", "network"),
    ("cargo", "bin_list", "project-code"),
    ("cargo", "crates_io_search", "network"),
    ("cargo", "dependencies", "maybe-network"),
    ("cargo", "features_generators", "project-code"),
    ("cargo", "read_manifest", "project-code"),
    ("cargo", "spec", "project-code"),
    ("cargo", "target_list", "project-code"),
    ("cargo", "test_list", "maybe-network"),
    ("cargo", "test_targets", "project-code"),
    ("chown", "users_or_groups", "unverified-tool"),
    ("claude", "installed_plugins", "env-network-likely"),
    ("claude", "mcp_servers", "maybe-network"),
    ("clear-variable", "get_variable_names", "unverified-tool"),
    ("codex", "cloud_tasks", "network"),
    ("codex", "feature_flags", "env-network-likely"),
    ("codex", "mcp_servers", "env-network-likely"),
    ("conda", "get_conda_configs", "project-code"),
    ("conda", "get_conda_environments", "project-code"),
    ("conda", "get_installed_packages", "project-code"),
    ("copilot", "cat_copilot_workspace", "unverified-tool"),
    ("cordova", "cat_package_json", "unverified-tool"),
    ("cordova", "plugin_list", "project-code"),
    ("dd", "conv_remaining", "unverified-tool"),
    ("debug-process", "get_process_names", "unverified-tool"),
    ("defaults", "domain_generator", "unverified-tool"),
    ("degit", "github_user_repos", "network"),
    ("deno", "deno_binaries", "unverified-tool"),
    ("deno", "deno_versions", "network"),
    ("deno", "doc_json", "maybe-network"),
    ("deno", "lint", "env-network-likely"),
    ("deployctl", "deploy_versions", "network"),
    ("deta", "node12_node14_python3_7_python3", "unverified-tool"),
    ("dnf", "list_installed_packages", "env-network-likely"),
    ("dnf", "list_rpm_files_in_cwd", "env-network-likely"),
    ("docker", "all_docker_contexts", "unverified-tool"),
    ("docker", "from_as", "unverified-tool"),
    ("docker", "image_with_tags", "env-network-verified"),
    ("docker", "list_docker_secrets", "maybe-network"),
    ("docker", "list_docker_service_replicas", "maybe-network"),
    ("docker", "list_docker_services", "maybe-network"),
    ("docker", "list_docker_stacks", "maybe-network"),
    ("docker", "list_docker_swarm_nodes", "maybe-network"),
    ("docker", "search", "network"),
    ("docker-compose", "compose_services", "env-network-likely"),
    ("dotnet", "global_tools", "env-network-likely"),
    ("dtm", "list_plugins", "unverified-tool"),
    ("eb", "list", "network"),
    ("elm", "elm_packages", "network"),
    ("elm-review", "echo", "unverified-tool"),
    (
        "enter-pshostprocess",
        "get_process_names",
        "unverified-tool",
    ),
    ("esbuild", "loader", "unverified-tool"),
    ("eslint", "env_remaining", "unverified-tool"),
    (
        "eslint",
        "ls_node_modules_root_global",
        "env-network-verified",
    ),
    ("expo", "npms_search", "network"),
    ("expo", "sysctl_hw_ncpu", "unverified-tool"),
    ("expo", "xcodebuild_ios_xcodeproj", "maybe-network"),
    ("expo", "xcrun_xctrace_list_devices", "unverified-tool"),
    ("expo-cli", "npms_search", "network"),
    ("expo-cli", "sysctl_hw_ncpu", "unverified-tool"),
    ("expo-cli", "xcodebuild_ios_xcodeproj", "maybe-network"),
    ("expo-cli", "xcrun_xctrace_list_devices", "unverified-tool"),
    ("ffmpeg", "completions", "unverified-tool"),
    ("ffmpeg", "completions_devices", "unverified-tool"),
    ("fig-teams@latest", "teams_list", "network"),
    ("fig-teams@latest", "users_for_selected_team", "network"),
    ("file", "param_keys", "unverified-tool"),
    ("firebase", "project_aliases", "network"),
    ("fisher", "fish_fisher_list", "unverified-tool"),
    ("flutter", "channels", "maybe-network"),
    ("flutter", "emulators", "env-network-likely"),
    ("fly", "flyctl_list_apps", "network"),
    ("fly", "flyctl_list_orgs", "network"),
    ("flyctl", "list_apps", "network"),
    ("flyctl", "list_orgs", "network"),
    ("fnm", "ls", "unverified-tool"),
    ("fnm", "ls_remote", "network"),
    ("fvm", "releases", "maybe-network"),
    ("gcloud", "gcloud_accounts", "env-network-likely"),
    ("gcloud", "gcloud_components", "maybe-network"),
    ("gcloud", "gcloud_configurations", "env-network-likely"),
    ("gcloud", "gcloud_projects", "network"),
    ("gcloud", "gcloud_regions", "network"),
    ("gcloud", "gcloud_zones", "network"),
    ("get-help", "get_command_names", "unverified-tool"),
    ("get-process", "get_process_names", "unverified-tool"),
    ("get-variable", "get_variable_names", "unverified-tool"),
    ("gh", "api_graphql_string_viewer", "network"),
    ("gh", "list_alias", "unverified-tool"),
    ("gh", "list_pr", "network"),
    ("gh", "repo_list_owner", "network"),
    ("git", "files_for_staging", "project-code"),
    ("git", "get_changed_or_tracked_files", "project-code"),
    ("git-flow", "type_branches", "unverified-tool"),
    ("go", "tool_generator", "env-network-likely"),
    ("gpg", "completions", "unverified-tool"),
    ("gsutil", "gcloud_projects", "network"),
    ("gsutil", "gcs_buckets", "network"),
    ("heroku", "get_app_generator", "network"),
    ("hexo", "list_post_draft", "project-code"),
    ("hub", "status", "project-code"),
    ("hub", "status_staged_or_unstaged", "project-code"),
    ("hugo", "ls_archetypes", "unverified-tool"),
    ("hyper", "list", "unverified-tool"),
    ("id", "dscl_users", "unverified-tool"),
    ("ignite-cli", "ls_ignite_templates", "unverified-tool"),
    ("ip", "netns", "unverified-tool"),
    ("ip", "network_interfaces", "unverified-tool"),
    ("ip", "processes", "unverified-tool"),
    ("ip", "tunnel_interfaces", "unverified-tool"),
    ("j", "cat", "unverified-tool"),
    ("journalctl", "boots", "unverified-tool"),
    ("journalctl", "journal_field_matches", "unverified-tool"),
    ("journalctl", "journal_fields", "unverified-tool"),
    ("journalctl", "syslog_identifiers", "unverified-tool"),
    ("journalctl", "units", "unverified-tool"),
    ("journalctl", "user_units", "unverified-tool"),
    ("just", "recipes", "project-code"),
    ("just", "variables", "project-code"),
    ("kill", "process", "unverified-tool"),
    ("kill", "signal_name", "unverified-tool"),
    ("killall", "process_name", "unverified-tool"),
    ("killall", "user_name", "unverified-tool"),
    ("kool", "docker_compose_config", "env-network-likely"),
    ("kool", "run", "project-code"),
    ("kubecolor", "cluster", "unverified-tool"),
    ("kubecolor", "cluster_role", "cluster"),
    ("kubecolor", "context", "unverified-tool"),
    ("kubecolor", "deployments", "cluster"),
    ("kubecolor", "namespace", "cluster"),
    ("kubecolor", "node", "cluster"),
    ("kubecolor", "resource", "cluster"),
    ("kubecolor", "resource_type", "cluster"),
    ("kubecolor", "role", "cluster"),
    ("kubecolor", "running_pods", "cluster"),
    ("kubecolor", "type_or_type_slash_name", "cluster"),
    ("kubecolor", "user", "unverified-tool"),
    ("kubectl", "cluster", "unverified-tool"),
    ("kubectl", "cluster_role", "cluster"),
    ("kubectl", "context", "unverified-tool"),
    ("kubectl", "deployments", "cluster"),
    ("kubectl", "kubectl_builtin_completion", "cluster"),
    ("kubectl", "namespace", "cluster"),
    ("kubectl", "node", "cluster"),
    ("kubectl", "resource", "cluster"),
    ("kubectl", "resource_type", "cluster"),
    ("kubectl", "role", "cluster"),
    ("kubectl", "running_pods", "cluster"),
    ("kubectl", "type_or_type_slash_name", "cluster"),
    ("kubectl", "user", "unverified-tool"),
    ("kubectx", "context", "unverified-tool"),
    ("kubectx", "delete_context", "unverified-tool"),
    ("kubectx", "kubectx_context", "unverified-tool"),
    ("kubens", "context", "unverified-tool"),
    ("kubens", "kubens_context", "cluster"),
    ("lerna", "list_while_read_p", "project-code"),
    ("lerna", "ls", "project-code"),
    ("limactl", "list", "unverified-tool"),
    ("lsof", "pids", "unverified-tool"),
    ("lsof", "process_names", "unverified-tool"),
    ("lsof", "users", "unverified-tool"),
    ("mackup", "list", "unverified-tool"),
    ("make", "list_targets", "unverified-tool"),
    ("man", "list_man_pages", "unverified-tool"),
    ("man", "sections_remaining", "unverified-tool"),
    (
        "mdfind",
        "ls_library_saved_searches_savedsearch",
        "unverified-tool",
    ),
    ("meteor", "cat_meteor_packages", "env-network-likely"),
    ("meteor", "create", "maybe-network"),
    ("meteor", "list_platforms", "env-network-likely"),
    ("mix", "help", "project-code"),
    ("mosh", "cat_ssh_config", "unverified-tool"),
    ("mosh", "cat_ssh_known_hosts", "unverified-tool"),
    ("n", "lsr", "network"),
    ("nativescript", "nativescript_templates", "network"),
    ("networkquality", "networksetup", "unverified-tool"),
    ("nextflow", "downloaded_projects", "env-network-likely"),
    ("nextflow", "run_names", "env-network-likely"),
    ("ng", "list_projects", "env-network-likely"),
    ("ni", "npms_search", "network"),
    ("nmap", "network_interfaces", "unverified-tool"),
    ("nmap", "nse_scripts", "unverified-tool"),
    ("npm", "get_scripts_generator", "unverified-tool"),
    ("npm", "npm_registry_search", "network"),
    ("npm", "npms_search", "network"),
    ("npm", "workspace_generator", "project-code"),
    ("npx", "until_node_modules_do_cd", "unverified-tool"),
    ("nr", "until_package_json_do_cd", "unverified-tool"),
    ("ns", "nativescript_templates", "network"),
    ("nx", "apps", "project-code"),
    ("nx", "apps_and_libs", "project-code"),
    ("nx", "e2e_apps", "project-code"),
    ("nx", "installed_plugins", "project-code"),
    ("nx", "local_generators", "unverified-tool"),
    ("nx", "local_schematics", "unverified-tool"),
    ("nx", "plugin_list", "project-code"),
    ("nx", "workspace_targets", "project-code"),
    ("oc", "build_configs", "cluster"),
    ("oc", "cluster", "unverified-tool"),
    ("oc", "cluster_role", "cluster"),
    ("oc", "context", "unverified-tool"),
    ("oc", "deployments", "cluster"),
    ("oc", "namespace", "cluster"),
    ("oc", "node", "cluster"),
    ("oc", "oc_builtin_completion", "cluster"),
    ("oc", "projects", "cluster"),
    ("oc", "resource", "cluster"),
    ("oc", "resource_type", "cluster"),
    ("oc", "role", "cluster"),
    ("oc", "running_pods", "cluster"),
    ("oc", "type_or_type_slash_name", "cluster"),
    ("oc", "user", "unverified-tool"),
    ("okteto", "context_list", "env-network-likely"),
    ("okteto", "namespace_list", "network"),
    ("op", "account_list_json", "env-network-likely"),
    ("open", "mdfind", "unverified-tool"),
    ("open", "mdfind_while_read_line", "unverified-tool"),
    ("pacman", "list_all_packages", "unverified-tool"),
    ("pacman", "list_all_pkg_tar_files_in_cwd", "unverified-tool"),
    ("pacman", "list_installed_packages", "unverified-tool"),
    ("pandoc", "completions", "unverified-tool"),
    ("pandoc", "completions_list", "unverified-tool"),
    ("pandoc", "pandoc", "unverified-tool"),
    ("paru", "list_all_packages", "env-network-likely"),
    ("paru", "list_all_pkg_tar_files_in_cwd", "unverified-tool"),
    ("paru", "list_installed_packages", "unverified-tool"),
    ("pass", "entries", "unverified-tool"),
    ("pass", "entry_dirs", "unverified-tool"),
    ("phpunit-watcher", "tests", "project-code"),
    ("pip", "list_packages", "maybe-network"),
    ("pip3", "list_packages", "maybe-network"),
    ("pkill", "process_name", "unverified-tool"),
    ("pkill", "signal_name", "unverified-tool"),
    ("pkill", "user_name", "unverified-tool"),
    ("pnpm", "dependencies_generator", "unverified-tool"),
    ("pnpm", "get_scripts_generator", "unverified-tool"),
    ("pnpm", "npms_search", "network"),
    ("pnpm", "until_package_json_do_cd", "unverified-tool"),
    ("pnpm", "workspace_packages_generator", "unverified-tool"),
    ("pprof", "saved_profiles", "unverified-tool"),
    (
        "pre-commit",
        "cat_pre_commit_config_yaml",
        "unverified-tool",
    ),
    ("projj", "cat_projj_cache_json", "unverified-tool"),
    ("projj", "cat_projj_config_json", "unverified-tool"),
    ("pyenv", "global_list", "unverified-tool"),
    ("pyenv", "version_list", "unverified-tool"),
    ("quickmail", "template_listall", "env-network-likely"),
    ("r", "rscript_libpaths", "project-code"),
    ("rancher", "server", "unverified-tool"),
    ("rclone", "listremotes", "unverified-tool"),
    (
        "react-native",
        "android_get_devices_generator",
        "unverified-tool",
    ),
    ("react-native", "gradle_tasks_generator", "maybe-network"),
    (
        "react-native",
        "ios_get_devices_generator",
        "unverified-tool",
    ),
    (
        "react-native",
        "ios_get_devices_simulator_generator",
        "unverified-tool",
    ),
    (
        "react-native",
        "ios_get_devices_udid_generator",
        "unverified-tool",
    ),
    ("react-native", "worker_generator", "unverified-tool"),
    ("react-native", "xcode_config_generator", "maybe-network"),
    ("react-native", "xcode_scheme_generator", "maybe-network"),
    ("redwood", "until_redwood_toml_do_cd", "unverified-tool"),
    ("remove-variable", "get_variable_names", "unverified-tool"),
    ("robot", "for_i_in_robot", "unverified-tool"),
    ("robot", "test_cases", "unverified-tool"),
    ("robot", "variables", "unverified-tool"),
    ("ros2", "actions", "lan"),
    ("ros2", "executables", "unverified-tool"),
    ("ros2", "interfaces", "unverified-tool"),
    ("ros2", "nodes", "lan"),
    ("ros2", "packages", "unverified-tool"),
    ("ros2", "services", "lan"),
    ("ros2", "topics", "lan"),
    ("rush", "npms_search", "network"),
    ("rush", "until_rush_json_do_cd", "unverified-tool"),
    ("rushx", "until_package_json_do_cd", "unverified-tool"),
    ("scc", "completions", "unverified-tool"),
    ("scc", "format_multi", "unverified-tool"),
    ("scp", "hosts", "unverified-tool"),
    ("scp", "remote_paths", "network"),
    ("screen", "detached_sessions", "unverified-tool"),
    ("screen", "sessions", "unverified-tool"),
    ("sdk", "available_versions", "network"),
    ("sdk", "candidates", "unverified-tool"),
    ("sdk", "installed_versions", "unverified-tool"),
    ("set-variable", "get_variable_names", "unverified-tool"),
    ("sftp", "cat_ssh_config", "unverified-tool"),
    ("sftp", "cat_ssh_known_hosts", "unverified-tool"),
    ("shortcuts", "list", "unverified-tool"),
    ("shortcuts", "list_shortcuts", "unverified-tool"),
    ("softwareupdate", "completions", "network"),
    ("ssh", "addresses", "unverified-tool"),
    ("ssh", "hosts", "unverified-tool"),
    ("ssh", "known_hosts", "unverified-tool"),
    ("st2", "users_or_groups", "unverified-tool"),
    ("stepzen", "github_schemas", "network"),
    ("stepzen", "list_schemas", "network"),
    ("sysctl", "completions", "unverified-tool"),
    ("systemctl", "unit_states", "unverified-tool"),
    ("systemctl", "unit_types", "unverified-tool"),
    ("systemctl", "units", "unverified-tool"),
    ("tailscale", "peers_colon", "unverified-tool"),
    ("tailscale", "status", "unverified-tool"),
    ("tar", "list_tar_files", "unverified-tool"),
    (
        "tccutil",
        "mdfind_applications_while_read",
        "unverified-tool",
    ),
    ("tcpdump", "interfaces", "unverified-tool"),
    ("tcpdump", "user_name", "unverified-tool"),
    ("terraform", "address_list", "maybe-network"),
    ("terraform", "output_list", "maybe-network"),
    ("terraform", "workspace_list", "maybe-network"),
    ("terragrunt", "state_list", "maybe-network"),
    ("terragrunt", "workspace_list", "maybe-network"),
    ("tfenv", "list", "unverified-tool"),
    ("tfenv", "list_remote", "network"),
    ("tfsec", "terraform_workspace_list", "maybe-network"),
    ("timedatectl", "timezones", "unverified-tool"),
    ("tmux", "buffer_name", "unverified-tool"),
    ("tmux", "src_pane", "unverified-tool"),
    ("tmux", "target_client", "unverified-tool"),
    ("tmux", "target_session", "unverified-tool"),
    ("tmux", "window_name", "unverified-tool"),
    ("tmuxinator", "projects", "unverified-tool"),
    ("tmuxinator", "session_names", "unverified-tool"),
    ("tns", "nativescript_templates", "network"),
    ("tokei", "completions", "unverified-tool"),
    ("trex", "cat_import_map_json", "unverified-tool"),
    ("trex", "cat_run_json", "unverified-tool"),
    ("trivy", "pkg_types_remaining", "unverified-tool"),
    ("trivy", "scanners_remaining", "unverified-tool"),
    ("trivy", "severity_remaining", "unverified-tool"),
    ("tsh", "clusters", "network"),
    ("tsh", "nodes", "network"),
    ("tsh", "status_user", "env-network-likely"),
    ("turbo", "until_turbo_json_do_cd", "unverified-tool"),
    ("uv", "installed_pythons", "project-code"),
    ("uv", "pip_installed_packages", "project-code"),
    ("uv", "project_dependencies", "project-code"),
    ("uv", "python_versions", "project-code"),
    ("vagrant", "vagrant_boxes", "unverified-tool"),
    ("vagrant", "vagrant_machines", "unverified-tool"),
    ("vite", "ls", "unverified-tool"),
    ("vr", "completions", "unverified-tool"),
    ("vultr-cli", "instance_list", "network"),
    ("wait-process", "get_process_names", "unverified-tool"),
    ("watson", "log", "unverified-tool"),
    ("watson", "projects", "unverified-tool"),
    ("watson", "tags", "unverified-tool"),
    ("wd", "cat_warprc", "unverified-tool"),
    (
        "wifi-password",
        "networksetup_wi_fi_getline_print_networksetup",
        "unverified-tool",
    ),
    ("yarn", "all_dependencies_generator", "env-network-verified"),
    ("yarn", "config_list", "env-network-verified"),
    ("yarn", "create_package_search", "network"),
    ("yarn", "dependencies_generator", "unverified-tool"),
    ("yarn", "executables_within_node_modules", "unverified-tool"),
    (
        "yarn",
        "get_global_packages_generator",
        "env-network-verified",
    ),
    ("yarn", "get_scripts_generator", "unverified-tool"),
    ("yarn", "npms_search", "network"),
    ("yarn", "workspace_names_generator", "env-network-verified"),
    ("yay", "list_all_packages", "env-network-likely"),
    ("yay", "list_all_pkg_tar_files_in_cwd", "unverified-tool"),
    ("yay", "list_installed_packages", "unverified-tool"),
    ("yc", "yc_builtin_completion", "maybe-network"),
    ("yo", "completions", "env-network-likely"),
    ("youtube-dl", "flat_playlist", "network"),
    ("youtube-dl", "pbpaste", "unverified-tool"),
];

/// Alias generators that must not run, with the class. An alias generator is a command the
/// completion engine runs to expand an alias typed by the user.
pub(super) const DENIED_ALIAS_GENERATORS: &[(&str, &str, &str)] = &[
    ("npm", "script_alias", "env-network-verified"),
    ("yarn", "script_alias", "env-network-verified"),
];
