#!/usr/bin/env bash
#
# Installs all cargo-managed dependencies required to build and test Warp.

"$PWD"/script/install_cargo_build_deps

"$PWD"/script/install_cargo_binstall

# Install nextest, which we use as our test execution harness.
cargo binstall --secure --no-confirm --no-discover-github-token cargo-nextest
