[package]
name = "persistence"
edition = "2024"
authors.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
diesel = { workspace = true, features = [
    "chrono",
    "32-column-tables",
] }
diesel_migrations = "2.2.0"

[dev-dependencies]
diesel = { workspace = true, features = ["sqlite", "chrono"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.33.0", features = ["bundled"] }
