[package]
name = "warp_server_auth"
version = "0.1.0"
edition = "2024"
authors.workspace = true
publish.workspace = true
license.workspace = true

[features]
integration_tests = []
test-util = []

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cynic.workspace = true
lasso.workspace = true
log.workspace = true
parking_lot.workspace = true
serde.workspace = true
warp_errors.workspace = true
